### ISSUE TITLE
Printing root passwords of hosts into output during adding host

### ISSUE THREAD

**Issue by pkubica** [oVirt/ovirt-ansible-infra#10]
When using infra role, root passwords of added hosts are printed into output with verbosity 0

TASK [oVirt.infra/roles/oVirt.hosts : Add hosts] *******************************
changed: [localhost] => (item={u'cluster': u'Default', u'password': u'123456', u'name': u'myhost1', u'address': u'192.168.0.200'})
changed: [localhost] => (item={u'cluster': u'Default', u'password': u'123456, u'name': u'myhost1', u'address': u'192.168.0.201'})
changed: [localhost] => (item={u'cluster': u'Default', u'password': u'123456', u'name': u'myhost1', u'address': u'192.168.0.202'})

It might be a bug of Ansible: 
https://github.com/ansible/ansible/issues/33912

**Comment by machacekondra** [comment]
Let's just use `loop_control` to WA this issue.
