### ISSUE TITLE
Consider the ability to add more than one datacenter

### ISSUE THREAD

**Issue by machacekondra** [oVirt/ovirt-ansible-infra#19]
Currently the ovirt-dataceneters role expects to deal with one data center.
to be more salable, we need maybe to consider to have a list of datacenters.

**Comment by machacekondra** [comment]
Moved from: https://github.com/oVirt/ovirt-ansible/issues/25

**Comment by leifmadsen** [comment]
Ultimately shouldn't this be dealt with in the wrapper playbook? You can call this via `include_role` and loop over it from your wrapper playbook to deal with the addition of multiple datacenters. The role itself shouldn't ultimately need to deal with the list as you can pass that in with a loop.

I haven't tried that yet, but I'm pretty sure it's more of a documentation problem than a role problem.
