### ISSUE TITLE
add 'hosted_engine' parameter to host

### ISSUE THREAD

**Issue by ThomasADavis** [oVirt/ovirt-ansible-infra#24]
- name: Add hosts
  ovirt_hosts:
    auth: "{{ ovirt_auth }}"
    state: "{{ item.state | default(omit) }}"
    name: "{{ item.name }}"
    address: "{{ item.address }}"
    cluster: "{{ item.cluster }}"
    password: "{{ item.password | default(omit) }}"
    public_key: "{{ item.public_key | default(omit) }}"
    override_iptables: true
    timeout: "{{ item.timeout | default(ovirt_hosts_add_timeout) }}"
    poll_interval: "{{ item.poll_interval | default(20) }}"
  with_items:
    - "{{ hosts | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  async: "{{ ovirt_hosts_max_timeout }}"
  poll: 0
  register: add_hosts
  tags:
    - hosts

'hosted_engine' deploy can only happen when the host is added; and if you've enabled gluster management in the cluster that has the hosted engine, and you want to add that node to the hosted-engine, you have to rebuild from scratch if the node is also running glusterfs-server.

**Comment by machacekondra** [comment]
Fixed by: https://github.com/oVirt/ovirt-ansible-infra/pull/25
