### ISSUE TITLE
Rename `hosts` varible as it's reserverd variable which keeps hosts in a play

### ISSUE THREAD

**Issue by machacekondra** [oVirt/ovirt-ansible-infra#41]
We need to rename the `hosts` variable, which is reserved by Ansible and keeps hosts in a play. Currently when running the play it produces following warning:
 
```[WARNING]: Found variable using reserved name: hosts```

We will keep `hosts` variable, so we keep backward compatibility but introduce also new variable.

**Comment by mnecas** [comment]
fixed in https://github.com/oVirt/ovirt-ansible-infra/pull/74
